services:
  master-relax:
    container_name: master-relax-app-prod
    build:
      context: ./
    env_file:
      - ./.env.production
    image: bering152/master-relax-app:latest
    restart: unless-stopped
    ports:
      - 3010:3000
