import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Master Relax",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <head>
        <link rel="icon" type="image/x-icon" href="/icons/master-relax.ico" />
      </head>
      <body className="min-h-screen">{children}</body>
    </html>
  );
}
