import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/components/shared/header';
import { Footer } from '@/components/shared/footer';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: 'Master Relax',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <head>
        <link rel="icon" type="image/x-icon" href="/icons/master-relax.ico" />
      </head>
      <body className="min-h-screen">
        <Toaster
          toastOptions={{
            style: {
              background: 'var(--primary)',
              color: '#fff',
            },
          }}
        />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
